### ISSUE TITLE
module00 ex02

### ISSUE THREAD

**Issue by Xyckens** [Axel-ex/SEAME-WarmUp-24-25#3]
For the exercise of converting strings, the output of the converted text and the error message of invalid numbers where missing the '\n' at the end.

Since the example shown in the subject dont have quotes, more than 3 arguments cant be denied:
![image](https://github.com/user-attachments/assets/7b534ab3-bf1e-421c-986a-f16eb5ba5fda)
, I'm submitting a suggested corrected code, also posting it here. 

`
#include <cstring>
#include <iostream>
#include <string>

void print_usage(void)
{
    std::cout
        << "Invalid number of arguments provided: ./convert <command> <string>" << std::endl;
    exit(EXIT_FAILURE);
}

int main(int argc, char** argv)
{
    if (argc <= 3)
        print_usage();

    std::string command = argv[1];
    std::string str = argv[2];
    for (int i = 3; i < argc; i++)
        str += " " + std::string(argv[i]); 

    if (command == "up" || command == "down")
    {
        if (command == "up")
            for (char letter : str)
                std::cout << static_cast<char>(std::toupper(letter));
        else if (command == "down")
            for (char letter : str)
                std::cout << static_cast<char>(std::tolower(letter));
        std::cout << std::endl;
    }
    else
        std::cout << "Error: unrecognized command" << std::endl;
}
`

**Comment by Axel-ex** [comment]
Just corrected it!
